on:
  push:
    branches: [main]

  jobs:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Force Failure
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
